if (GetLocale() ~= "deDE") then return end
local myName, me = ...
local L = me.L


L[myName] = "|cff0088ffShowBiSPaladin|cff808080: |r"


--PALADINHoly
L["PALADINHoly"] = "|cffd6266cShowBiSPaladin|r\n \n.: Einhändig :. > |cff0070ddZaubergesegneter Säbel|r > Akademie von Algeth'ar \n \n.: Schildhand :. > |cff0070ddKristallisiertes Bollwerk|r > Das Azurblaue Gewölbe \n \n.: Kopf :. > |cff0070ddGoldstahlgroßhelm|r > Schattenmondgrabstätte \n \n.: Hals :. > |cff0070ddGeistbrecheranhänger|r > Tempel der Jadeschlange \n \n.: Schulter :. > |cff0070ddSchulterstücke der Nokhudtraditionalisten|r > Der Angriff der Nokhud \n \n.: Umhang :. > |cff0070ddTrankbefleckter Umhang|r > Akademie von Algeth'ar \n \n.: Brust :. > |cff0070ddInfernobrustplatte|r > Der Hof Der Sterne \n \n.: Handgelenk :. > |cff0070ddGoldstahlbindungen|r > Schattenmondgrabstätte \n \n.: Hände :. > |cff0070ddGoldstahlhandschuhe|r > Schattenmondgrabstätte \n \n.: Taille :. > |cff0070ddGroßgürtel der hierarchischen Vorherrschaft|r > Die Hallen der Tapferkeit \n \n.: Beine :. > |cff0070ddBeinschützer des geschätzten Professors|r > Akademie von Algeth'ar \n \n.: Füße :. > |cff0070dd22-Leugen-Schreiter|r > Das Azurblaue Gewölbe \n \n.: Finger :. > |cff0070ddInstabile Arkanschleife|r > Das Azurblaue Gewölbe \n \n.: Finger :. > |cff0070ddDonnernder Starkregenring|r > Der Angriff der Nokhud \n \n.: Schmuck :. > |cff0070ddSingender Stein als Miniatur|r > Der Angriff der Nokhud \n \n.: Schmuck :. > |cff0070ddFläschchen der ehrwürdigen Nacht|r > Der Hof Der Sterne"

--PALADINProtection
L["PALADINProtection"] = "|cffd6266cShowBiSPaladin|r\n \n.: Einhändig :. > |cff0070ddDoppelschlag|r > Der Angriff der Nokhud \n \n.: Schildhand :. > |cff0070ddKristallisiertes Bollwerk|r > Das Azurblaue Gewölbe \n \n.: Kopf :. > |cff0070ddHelm der ehrfurchtsvollen Treue|r > Der Hof Der Sterne \n \n.: Hals :. > |cff0070ddPerlen der Ukhelahnen|r > Der Angriff der Nokhud \n \n.: Schulter :. > |cff0070ddSchulterstücke des Allvaters|r > Die Hallen der Tapferkeit \n \n.: Umhang :. > |cff0070ddFeuerfestes Tuch|r > Rubinlebensbecken \n \n.: Brust :. > |cff0070ddKürass des irreparablen Wahnsinns|r > Das Azurblaue Gewölbe \n \n.: Handgelenk :. > |cff0070ddGoldstahlbindungen|r > Schattenmondgrabstätte \n \n.: Hände :. > |cff0070ddGoldstahlhandschuhe|r > Schattenmondgrabstätte \n \n.: Taille :. > |cff0070ddGroßgürtel der hierarchischen Vorherrschaft|r > Die Hallen der Tapferkeit \n \n.: Beine :. > |cff0070ddBeinschützer des Drachenjägers|r > Der Angriff der Nokhud \n \n.: Füße :. > |cff0070ddBeschützergroßstiefel der Valkyra|r > Die Hallen der Tapferkeit \n \n.: Finger :. > |cff0070ddJuwelensignet von Melandrus|r > Der Hof Der Sterne \n \n.: Finger :. > |cff0070ddDonnernder Starkregenring|r > Der Angriff der Nokhud \n \n.: Schmuck :. > |cff0070ddGranyths robuste Schuppe|r > Der Angriff der Nokhud \n \n.: Schmuck :. > |cff0070ddHorn der Ehre|r > Die Hallen der Tapferkeit"

--PALADINRetribution
L["PALADINRetribution"] = "|cffd6266cShowBiSPaladin|r\n \n.: Zweihändig :. > |cff0070ddLeyliniensucher|r > Akademie von Algeth'ar \n \n.: Kopf :. > |cff0070ddHelm der ehrfurchtsvollen Treue|r > Der Hof Der Sterne \n \n.: Hals :. > |cff0070ddPerlen der Ukhelahnen|r > Der Angriff der Nokhud \n \n.: Schulter :. > |cff0070ddSchulterstücke des Allvaters|r > Die Hallen der Tapferkeit \n \n.: Umhang :. > |cff0070ddFeuerfestes Tuch|r > Rubinlebensbecken \n \n.: Brust :. > |cff0070ddKürass des irreparablen Wahnsinns|r > Das Azurblaue Gewölbe \n \n.: Handgelenk :. > |cff0070ddSkoldiirarmschienen|r > Der Hof Der Sterne \n \n.: Hände :. > |cff0070ddStulpen des Arkanverteidigers|r > Der Hof Der Sterne \n \n.: Taille :. > |cff0070ddTaillenschutz der tosenden Brise|r > Der Hof Der Sterne \n \n.: Beine :. > |cff0070ddBeinschützer des Drachenjägers|r > Der Angriff der Nokhud \n \n.: Füße :. > |cff0070ddSteintrittstiefel|r > Tempel der Jadeschlange \n \n.: Finger :. > |cff0070ddJuwelensignet von Melandrus|r > Der Hof Der Sterne \n \n.: Finger :. > |cff0070ddInstabile Arkanschleife|r > Das Azurblaue Gewölbe"
